### ISSUE TITLE
c'est nul

### ISSUE THREAD

**Issue by valdn** [CastelJeremy/todo.sh#1]
menfou

**Comment by CastelJeremy** [comment]
Bonjour monsieur @valdn,

Je vous demanderais de ne plus venir commenter de message négatif sur mes projets informatique.

En vous souhaitant une bonne fin de journée.

**Comment by valdn** [comment]
https://user-images.githubusercontent.com/45600740/222920332-7f5732c0-0e21-4b49-8e5c-9c404b240f0a.mp4
