### ISSUE TITLE
Bad Sanitize of to-do's labels

### ISSUE THREAD

**Issue by eliotmasset** [CastelJeremy/todo.sh#2]
When I switch 2 lines with chars containing a back-slash ("\\"), an error occure and the switch not work.

**Exemple :** 

`todo -a "xxxs/yyy"`

> 01 xxx
> 02 xxx
> 03 xxx
> 04 xxxs/yyy

`todo -s 1 4`

> sed: -e expression n°1, caractère 24: option inconnue pour « s »

...

**Comment by CastelJeremy** [comment]
Should be fixed with the latest commit
